CREATE TABLE image_user
(
  FK_IMAGE_ID bigint(20)  NOT NULL,
  FK_USER_ID  bigint(20)  NOT NULL,
  CDATE       datetime(6) NOT NULL,
  UDATE       datetime(6) NOT NULL,
  PROFILE     bit(1)      NOT NULL DEFAULT b'0',
  PRIMARY KEY (FK_IMAGE_ID, FK_USER_ID),
  KEY FKIMAGE_USER511672 (FK_USER_ID),
  CONSTRAINT FKIMAGE_USER511672 FOREIGN KEY (FK_USER_ID) REFERENCES user (ID),
  CONSTRAINT FKIMAGE_USER75242 FOREIGN KEY (FK_IMAGE_ID) REFERENCES image (ID)
) 