CREATE TABLE entry
(
  ID                 bigint(20)   NOT NULL AUTO_INCREMENT,
  FK_ENTRY_PARENT_ID bigint(20) DEFAULT NULL,
  FK_PAGE_ID         bigint(20) DEFAULT NULL,
  FK_MENU_ID         bigint(20) DEFAULT NULL,
  LABEL              varchar(100) NOT NULL,
  CDATE              datetime(6)  NOT NULL,
  UDATE              datetime(6)  NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_ENTRY_PARENT_ID_idx (FK_ENTRY_PARENT_ID),
  KEY FK_MENU_ID_idx (FK_MENU_ID),
  KEY FK_SUBENTRY_ID (FK_PAGE_ID),
  CONSTRAINT CSTR_FK_ENTRY_PARENT_ID FOREIGN KEY (FK_ENTRY_PARENT_ID) REFERENCES entry (ID),
  CONSTRAINT FK_MENU_ID FOREIGN KEY (FK_MENU_ID) REFERENCES menu (ID),
  CONSTRAINT FK_SUBENTRY_ID FOREIGN KEY (FK_PAGE_ID) REFERENCES page (ID)
)