CREATE TABLE message
(
  ID              bigint(20)  NOT NULL AUTO_INCREMENT,
  FK_USER_ID_FROM bigint(20)   DEFAULT NULL,
  FK_USER_ID_TO   bigint(20)  NOT NULL,
  FK_STATUS_ID    bigint(20)  NOT NULL,
  RESPONSE_EMAIL  varchar(255) DEFAULT NULL,
  MESSAGE         text        NOT NULL,
  CDATE           datetime(6) NOT NULL,
  UDATE           datetime(6) NOT NULL,
  PRIMARY KEY (ID),
  KEY FKMESSAGE241606 (FK_STATUS_ID),
  KEY FKMESSAGE423697 (FK_USER_ID_FROM),
  KEY FKMESSAGE853733 (FK_USER_ID_TO),
  CONSTRAINT FKMESSAGE241606 FOREIGN KEY (FK_STATUS_ID) REFERENCES status (ID),
  CONSTRAINT FKMESSAGE423697 FOREIGN KEY (FK_USER_ID_FROM) REFERENCES user (ID),
  CONSTRAINT FKMESSAGE853733 FOREIGN KEY (FK_USER_ID_TO) REFERENCES user (ID)
)