CREATE TABLE page_type
(
  ID           bigint(20)  NOT NULL AUTO_INCREMENT,
  LAYOUT_TITLE varchar(100) DEFAULT NULL,
  LAYOUT_NAME  varchar(100) DEFAULT NULL,
  FK_IMAGE_ID  bigint(20)   DEFAULT NULL,
  CDATE        datetime(6) NOT NULL,
  UDATE        datetime(6) NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_IMAGE_ID_idx (FK_IMAGE_ID),
  CONSTRAINT FK_IMAGE_ID FOREIGN KEY (FK_IMAGE_ID) REFERENCES image(ID)
) 