CREATE TABLE page_authority
(
  FK_AUTHORITY_ID bigint(20) NOT NULL,
  FK_PAGE_ID      bigint(20) NOT NULL,
  PRIMARY KEY (FK_AUTHORITY_ID, FK_PAGE_ID),
  KEY FKPAGE_AUTHO676317 (FK_PAGE_ID),
  CONSTRAINT FKPAGE_AUTHO676317 FOREIGN KEY (FK_PAGE_ID) REFERENCES page (ID),
  CONSTRAINT FKPAGE_AUTHO939906 FOREIGN KEY (FK_AUTHORITY_ID) REFERENCES authority (ID)
) 