CREATE TABLE SUBPAGE
(
  FK_PAGE_ID_PARENT bigint(20) NOT NULL,
  FK_PAGE_ID_CHILD  bigint(20) NOT NULL,
  PRIMARY KEY (FK_PAGE_ID_PARENT, FK_PAGE_ID_CHILD),
  KEY FKSUBPAGE921558 (FK_PAGE_ID_CHILD),
  CONSTRAINT FKSUBPAGE560386 FOREIGN KEY (FK_PAGE_ID_PARENT) REFERENCES page (ID),
  CONSTRAINT FKSUBPAGE921558 FOREIGN KEY (FK_PAGE_ID_CHILD) REFERENCES page (ID)
) 