CREATE TABLE IMAGE_PAGE
(
  FK_IMAGE_ID bigint(20) NOT NULL,
  FK_PAGE_ID  bigint(20) NOT NULL,
  PRIMARY KEY (FK_IMAGE_ID, FK_PAGE_ID),
  KEY FKIMAGE_PAGE260805 (FK_PAGE_ID),
  CONSTRAINT FKIMAGE_PAGE260805 FOREIGN KEY (FK_PAGE_ID) REFERENCES page (ID),
  CONSTRAINT FKIMAGE_PAGE909037 FOREIGN KEY (FK_IMAGE_ID) REFERENCES image (ID)
) 