CREATE TABLE script
(
  ID    bigint(20)   NOT NULL AUTO_INCREMENT,
  TITLE varchar(200) NOT NULL,
  PATH  varchar(200),
  VALUE text,
  CDATE datetime(6)  NOT NULL,
  UDATE datetime(6)  NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE page_script
(
  FK_PAGE_ID bigint(20),
  FK_SCRIPT_ID bigint(20),
  PRIMARY KEY (FK_PAGE_ID, FK_SCRIPT_ID),
  CONSTRAINT CSTR_PAGE_SCRIPT_FK_PAGE_ID FOREIGN KEY (FK_PAGE_ID) REFERENCES page(ID),
  CONSTRAINT CSTR_PAGE_SCRIPT_FK_SCRIPT_ID FOREIGN KEY(FK_SCRIPT_ID) REFERENCES script(ID)
);

CREATE TABLE stylesheet
(
  ID    bigint(20)   NOT NULL AUTO_INCREMENT,
  TITLE varchar(200) NOT NULL,
  PATH  varchar(200),
  VALUE text,
  CDATE datetime(6)  NOT NULL,
  UDATE datetime(6)  NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE page_stylesheet
(
  FK_PAGE_ID bigint(20),
  FK_STYLESHEET_ID bigint(20),
  PRIMARY KEY (FK_PAGE_ID, FK_STYLESHEET_ID),
  CONSTRAINT CSTR_PAGE_STYLESHEET_FK_PAGE_ID FOREIGN KEY (FK_PAGE_ID) REFERENCES page(ID),
  CONSTRAINT CSTR_PAGE_STYLESHEET_FK_STYLESHEET_ID FOREIGN KEY(FK_STYLESHEET_ID) REFERENCES stylesheet(ID)
);