ALTER TABLE file
ADD MIME VARCHAR(100) NOT NULL;
ALTER TABLE file
DROP COLUMN ENABLED;
ALTER TABLE file
DROP COLUMN EXTENSION;
ALTER TABLE file
ADD PATH VARCHAR(255) NOT NULL;
ALTER TABLE file MODIFY COLUMN MIME VARCHAR(100) AFTER DATA;
ALTER TABLE file MODIFY COLUMN PATH VARCHAR(255) AFTER NAME;
ALTER TABLE file MODIFY COLUMN DESCRIPTION VARCHAR(200) AFTER MIME;