spring:
  datasource:
    url: jdbc:mysql://jba.ckrms4qkskz1.eu-west-3.rds.amazonaws.com:3306/opencms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: opencms
    password: n86TgiYq9F2DwxB
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: aws,security
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
server:
  port: 5000
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    use-relative-redirects: true
  use-forward-headers: true