application:
  opencms:
    web:
      extension: .s3.eu-west-3.amazonaws.com/
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://localhost:3306/opencmstest?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: opencms
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
server:
  port: 8080