server:
  port: 5000
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    use-relative-redirects: true
  use-forward-headers: true
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://localhost:3306/opencms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: homecloud,security
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}